### PR TITLE
Support Sign in with Apple

### PR DESCRIPTION
**Pull request by derwaldgeist**
This is a working version of Sign in with Apple tested with the `quave:accounts-apple` package. I haven't tested it with the `bigowl:accounts-apple` package  yet, but as they are nearly identical (the `quave` version adds a Cordova native workflow), I am pretty confident this package will work as well.

There are two caveats, however:

The workflow fails on macOS / iOS Safari, since these browsers uses a native login dialog instead of a popup. After the login succeeds, the redirect URI replaces the page and thus creates a new user instead, like in a regular login / signup scenario. I haven't found a way yet to avoid this. 

And another purely cosmetic one: `quave:accounts-apple` has changed the signature of the `requestCredential()` method in order to add a native callback as well. Unfortunately, they put this native callback at the second parameter position instead of the third, so I flipped these to be compatible with the default behavior of `Meteor.linkWith<Service>`, as you can see here:

https://github.com/marblear/meteor-link-accounts/blob/feature/sign-in-with-apple/community-services/apple.js#L4
https://github.com/marblear/meteor-link-accounts/blob/feature/sign-in-with-apple/community-services/apple.js#L24

I have filed a change request here:
https://github.com/quavedev/apple-oauth/issues/7
to align both signatures.

I leave it up to you if you would want to merge this PR right away or await their feedback.

This new callback should also be mentioned in the docs, I guess.

### CODE REVIEW

**Comment by yubozhao** [comment]
This is an awesome add-on.
@StorytellerCZ , if you have a chance, take a look?

**Comment by StorytellerCZ** [comment]
So far, so good, but we need to fix the workflow for Apple devices (macOS and iOS Safari) as you mentioned.

**Comment by derwaldgeist** [comment]
I agree, #58 should be fixed to make it fully useable, macOS and iOS are important platforms for this sign in method. I can add a section to the readme, but I am currently under heavy load. Pls ping me again if it takes too long.

**Review by StorytellerCZ — APPROVED** [review]
Code looks good, just need to fix the redirect issue.

**Pull request merged**
